"""
This type stub file was generated by pyright.
"""

class ChangeSet:
    def __init__(self, _change_set=...) -> None:
        ...
    
    def add_change(self, entity_id, entity_urn, property): # -> None:
        ...
    
    def entity_deleted(self, _entity_id): # -> None:
        ...
    
    def get_changed_properties(self, _entity_id): # -> list[Any]:
        ...
    
    def get_changed_property(self, _entity_id, prop_urn): # -> None:
        ...
    
    def get_changed_entities(self): # -> dict_keys[Any, Any]:
        ...
    
    def get_deleted_entities(self): # -> set[Any]:
        ...
    
    def get_entity_urn(self, _entity_id): # -> None:
        ...
    
    def merge(self, _change_set): # -> None:
        ...
    


