"""
This type stub file was generated by pyright.
"""

class EntityID:
    def __init__(self, id: int) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def get_value(self): # -> <subclass of int and EntityID> | int:
        ...
    
    def __str__(self) -> str:
        ...
    
    def equals(self, o): # -> bool:
        ...
    


