"""
This type stub file was generated by pyright.
"""

from rcrs_core.messages.message import Message

class AKConnect(Message):
    def __init__(self) -> None:
        ...
    
    def write(self, request_id, agent): # -> MessageProto:
        ...
    
    def read(self): # -> None:
        ...
    


