"""
This type stub file was generated by pyright.
"""

class ControlMessageFactory:
    def __init__(self) -> None:
        ...
    
    def make_message(self, msg): # -> KASense | KAConnectOK | KAConnectError | Shutdown | None:
        ...
    


