"""
This type stub file was generated by pyright.
"""

from rcrs_core.messages.message import Message

class KAConnectError(Message):
    def __init__(self, data) -> None:
        ...
    
    def read(self): # -> None:
        ...
    
    def write(self): # -> None:
        ...
    


