"""
This type stub file was generated by pyright.
"""

from rcrs_core.connection import RCRSProto_pb2
from rcrs_core.messages.message import Message

class KASense(Message):
    def __init__(self, data: RCRSProto_pb2) -> None:
        ...
    
    def read(self): # -> None:
        ...
    
    def write(self): # -> None:
        ...
    


