"""
This type stub file was generated by pyright.
"""

class Connection:
    def __init__(self, host, port) -> None:
        ...
    
    def connect(self): # -> None:
        ...
    
    def parseMessageFromKernel(self): # -> None:
        ...
    
    def message_received(self, agent_message_received): # -> None:
        ...
    
    def send_msg(self, msg): # -> None:
        ...
    


