"""
This type stub file was generated by pyright.
"""

""" utils to handle connection """
def write_int32(value, sock): # -> None:
    ...

def readnbytes(sock, n): # -> Literal[b""]:
    ...

def read_int32(sock): # -> int:
    ...

def write_msg(msg, sock): # -> None:
    ...

def read_msg(sock): # -> MessageProto:
    ...

