"""
This type stub file was generated by pyright.
"""

class Config:
    def __init__(self) -> None:
        ...
    
    def get_value(self, key: str) -> str | None:
        ...
    
    def get_value_or_default(self, key: str, default: str) -> str:
        ...
    
    def get_int_value(self, key: str) -> int | None:
        ...
    
    def get_int_value_or_default(self, key: str, default: int) -> int:
        ...
    
    def get_float_value(self, key) -> float | None:
        ...
    
    def get_float_value_or_default(self, key: str, default: float) -> float:
        ...
    
    def get_boolean_value(self, key) -> bool | None:
        ...
    
    def get_boolean_value_or_default(self, key: str, default: bool) -> bool:
        ...
    
    def get_array_value(self, key) -> list | None:
        ...
    
    def get_array_value_or_default(self, key: str, default: list) -> list:
        ...
    
    def set_value(self, key: str, value: str) -> None:
        ...
    
    def set_int_value(self, key: str, value: int) -> None:
        ...
    
    def set_float_value(self, key: str, value: float) -> None:
        ...
    
    def set_boolean_value(self, key: str, value: bool) -> None:
        ...
    
    def set_array_value(self, key: str, value: list) -> None:
        ...
    


