"""
This type stub file was generated by pyright.
"""

from rcrs_core.commands.Command import Command
from rcrs_core.worldmodel.entityID import EntityID

class AKClear(Command):
    def __init__(self, agent_id: EntityID, time: int, target: EntityID) -> None:
        ...
    
    def prepare_cmd(self): # -> MessageProto:
        ...
    


