"""
This type stub file was generated by pyright.
"""

from rcrs_core.commands.Command import Command
from rcrs_core.worldmodel.entityID import EntityID
from typing import List

class AKMove(Command):
    def __init__(self, agent_id: EntityID, time: int, path: List[int], destinationX=..., destinationY=...) -> None:
        ...
    
    def prepare_cmd(self): # -> MessageProto:
        ...
    


