"""
This type stub file was generated by pyright.
"""

from rcrs_core.commands.Command import Command
from rcrs_core.worldmodel.entityID import EntityID

class AKSpeak(Command):
    def __init__(self, agent_id: EntityID, time: int, message: str, channel: int) -> None:
        ...
    
    def prepare_cmd(self): # -> MessageProto:
        ...
    


