"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod

class Command(ABC):
    def __init__(self) -> None:
        ...
    
    @abstractmethod
    def prepare_cmd(): # -> None:
        ...
    


