"""
This type stub file was generated by pyright.
"""

from rcrs_core.properties.property import Property

class BooleanProperty(Property):
    def __init__(self, urn) -> None:
        ...
    
    def set_fields(self, value): # -> None:
        ...
    
    def copy(self): # -> BooleanProperty:
        ...
    
    def take_value(self, _property): # -> None:
        ...
    


