"""
This type stub file was generated by pyright.
"""

from rcrs_core.properties.property import Property
from rcrs_core.worldmodel.entityID import EntityID
from typing import List

class EntityIDListProperty(Property):
    def __init__(self, urn) -> None:
        ...
    
    def set_fields(self, data): # -> None:
        ...
    
    def set_value(self, _value: List[EntityID]): # -> None:
        ...
    
    def copy(self): # -> EntityIDListProperty:
        ...
    
    def take_value(self, _property): # -> None:
        ...
    


