"""
This type stub file was generated by pyright.
"""

from rcrs_core.properties.property import Property

class IntArrayProperty(Property):
    def __init__(self, urn) -> None:
        ...
    
    def set_fields(self, data): # -> None:
        ...
    
    def set_value(self, data): # -> None:
        ...
    
    def copy(self): # -> IntArrayProperty:
        ...
    
    def take_value(self, _property): # -> None:
        ...
    


