"""
This type stub file was generated by pyright.
"""

class Property:
    def __init__(self, _urn) -> None:
        ...
    
    def get_urn(self): # -> Any:
        ...
    
    def get_value(self): # -> None:
        ...
    
    def set_value(self, _value): # -> None:
        ...
    
    def to_string(self): # -> None:
        ...
    


