"""
This type stub file was generated by pyright.
"""

class StandardPropertyFactory:
    def __init__(self) -> None:
        ...
    
    def make_property(urn): # -> IntProperty | IntArrayProperty | BooleanProperty | EntityIDProperty | EntityIDListProperty | EdgeListProperty | None:
        ...
    


