"""
This type stub file was generated by pyright.
"""

from rcrs_core.entities.building import Building

class AmbulanceCentreEntity(Building):
    urn = ...
    def __init__(self, entity_id) -> None:
        ...
    
    def set_entity(self, properties): # -> None:
        ...
    
    def get_entity_name(self): # -> Literal['Ambulance Centre']:
        ...
    
    def copy_impl(self): # -> AmbulanceCentreEntity:
        ...
    


