"""
This type stub file was generated by pyright.
"""

from typing import List
from rcrs_core.entities.entity import Entity

class Area(Entity):
    def __init__(self, entity_id) -> None:
        ...
    
    def set_entity(self, properties): # -> None:
        ...
    
    def get_location(self): # -> tuple[Any | None, Any | None]:
        ...
    
    def get_neighbours(self): # -> list[Any]:
        ...
    
    def get_edge_to(self, neighbour): # -> Entity | None:
        ...
    
    def get_property(self, urn): # -> IntProperty | EdgeListProperty | EntityIDListProperty | None:
        ...
    
    def get_edges_property(self): # -> EdgeListProperty:
        ...
    
    def get_edges(self) -> List[Entity]:
        ...
    
    def set_edges(self, value): # -> None:
        ...
    
    def add_edge(self, edge): # -> None:
        ...
    
    def get_blockades_property(self): # -> EntityIDListProperty:
        ...
    
    def get_blockades(self): # -> None:
        ...
    
    def set_blockades(self, value): # -> None:
        ...
    
    def get_shape(self): # -> None:
        ...
    


