"""
This type stub file was generated by pyright.
"""

class Edge:
    def __init__(self, start_x, start_y, end_x, end_y, _neighbour) -> None:
        ...
    
    def get_start_x(self):
        ...
    
    def get_start_y(self):
        ...
    
    def get_end_x(self):
        ...
    
    def get_end_y(self):
        ...
    
    def is_passable(self): # -> bool:
        ...
    
    def get_neighbour(self): # -> None:
        ...
    
    def to_string(self):
        ...
    


