"""
This type stub file was generated by pyright.
"""

from rcrs_core.entities.entity import Entity
from rcrs_core.properties.entityIDProperty import EntityIDProperty
from rcrs_core.worldmodel.entityID import EntityID
from rcrs_core.worldmodel.worldmodel import WorldModel

class Human(Entity):
    def __init__(self, entity_id) -> None:
        ...
    
    def get_location(self, world_model: WorldModel): # -> None:
        ...
    
    def set_entity(self, properties: dict): # -> None:
        ...
    
    def get_property(self, urn): # -> EntityIDProperty | IntArrayProperty | IntProperty | None:
        ...
    
    def get_x_property(self): # -> IntProperty:
        ...
    
    def get_x(self) -> int:
        ...
    
    def set_x(self, value) -> None:
        ...
    
    def get_y_property(self): # -> IntProperty:
        ...
    
    def get_y(self): # -> None:
        ...
    
    def set_y(self, value): # -> None:
        ...
    
    def get_position_property(self) -> EntityIDProperty:
        ...
    
    def get_position(self) -> EntityID:
        ...
    
    def set_position(self, value): # -> None:
        ...
    
    def get_position_history_property(self): # -> IntArrayProperty:
        ...
    
    def get_position_history(self): # -> None:
        ...
    
    def set_position_history(self, value): # -> None:
        ...
    
    def get_direction_property(self): # -> IntProperty:
        ...
    
    def get_direction(self): # -> None:
        ...
    
    def set_direction(self, value): # -> None:
        ...
    
    def get_stamina_property(self): # -> IntProperty:
        ...
    
    def get_stamina(self): # -> None:
        ...
    
    def set_stamina(self, value): # -> None:
        ...
    
    def get_hp_property(self): # -> IntProperty:
        ...
    
    def get_hp(self): # -> None:
        ...
    
    def set_hp(self, value): # -> None:
        ...
    
    def get_damage_property(self): # -> IntProperty:
        ...
    
    def get_damage(self): # -> None:
        ...
    
    def set_damage(self, value): # -> None:
        ...
    
    def get_buriedness_property(self): # -> IntProperty:
        ...
    
    def get_buriedness(self): # -> None:
        ...
    
    def set_buriedness(self, value): # -> None:
        ...
    
    def get_travel_distance_property(self): # -> IntProperty:
        ...
    
    def get_travel_distance(self): # -> None:
        ...
    
    def set_travel_distance(self, value): # -> None:
        ...
    


