"""
This type stub file was generated by pyright.
"""

from rcrs_core.entities.road import Road

class Hydrant(Road):
    urn = ...
    def __init__(self, entity_id) -> None:
        ...
    
    def copy_impl(self): # -> Hydrant:
        ...
    
    def get_entity_name(self): # -> Literal['Hydrant']:
        ...
    
    def set_entity(self, properties): # -> None:
        ...
    


