"""
This type stub file was generated by pyright.
"""

from rcrs_core.entities.building import Building

class PoliceOfficeEntity(Building):
    urn = ...
    def __init__(self, entity_id) -> None:
        ...
    
    def copy_impl(self): # -> PoliceOfficeEntity:
        ...
    
    def get_entity_name(self): # -> Literal['Police office']:
        ...
    
    def set_entity(self, properties): # -> None:
        ...
    


