"""
This type stub file was generated by pyright.
"""

from rcrs_core.entities.building import Building

class Refuge(Building):
    urn = ...
    def __init__(self, entity_id) -> None:
        ...
    
    def set_entity(self, properties): # -> None:
        ...
    
    def copy_impl(self): # -> Refuge:
        ...
    
    def get_entity_name(self) -> str:
        ...
    
    def get_property(self, urn): # -> IntProperty | EdgeListProperty | EntityIDListProperty | None:
        ...
    
    def get_bed_capacity_property(self): # -> IntProperty:
        ...
    
    def get_bed_capacity(self): # -> None:
        ...
    
    def set_bed_capacity(self, value): # -> None:
        ...
    
    def get_occupied_beds_property(self): # -> IntProperty:
        ...
    
    def get_occupied_beds(self): # -> None:
        ...
    
    def set_occupied_beds(self, value): # -> None:
        ...
    
    def get_refill_capacity_property(self): # -> IntProperty:
        ...
    
    def get_refill_capacity(self): # -> None:
        ...
    
    def set_refill_capacity(self, value): # -> None:
        ...
    
    def get_waiting_list_size_property(self): # -> IntProperty:
        ...
    
    def get_waiting_list_size(self): # -> None:
        ...
    
    def set_waiting_list_size(self, value): # -> None:
        ...
    


