"""
This type stub file was generated by pyright.
"""

from rcrs_core.entities.area import Area

class Road(Area):
    urn = ...
    def __init__(self, entity_id) -> None:
        ...
    
    def set_entity(self, properties) -> None:
        ...
    
    def get_entity_name(self) -> str:
        ...
    
    def copy_impl(self): # -> Road:
        ...
    


