"""
This type stub file was generated by pyright.
"""

class StandardEntityFactory:
    _instance = ...
    def __new__(cls): # -> Self:
        ...
    
    def __init__(self) -> None:
        ...
    
    def make_entity(urn, id): # -> Building | Refuge | Road | Blockade | PoliceForceEntity | PoliceOfficeEntity | AmbulanceTeamEntity | AmbulanceCentreEntity | FireBrigadeEntity | FireStationEntity | Civilian | Hydrant | GasStation | None:
        ...
    


