"""
This type stub file was generated by pyright.
"""

class Logger:
    def __init__(self, _name, agent_id=...) -> None:
        ...
    
    def info(self, msg): # -> None:
        ...
    
    def debug(self, msg): # -> None:
        ...
    
    def error(self, msg): # -> None:
        ...
    
    def warning(self, msg): # -> None:
        ...
    
    def warn(self, msg): # -> None:
        ...
    
    def set_id(self, id): # -> None:
        ...
    


